# Generated by Django 3.0.8 on 2020-07-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50, verbose_name='域名')),
                ('ip', models.GenericIPAddressField(verbose_name='ip地址')),
                ('user', models.CharField(max_length=50, verbose_name='用户')),
                ('user_type', models.CharField(max_length=50, verbose_name='用户类型')),
            ],
            options={
                'db_table': 'db_server_info',
            },
        ),
    ]
